- alias: "MegaD Sensors update"
  trigger:
  - platform: time_pattern
    seconds: "0"
  condition: []
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.megad_state

- alias: "Night mode off"
  trigger:
  - platform: time
    at: "6:59:30"
  condition:
  - condition: state
    entity_id: climate.warm_floor
    state: heat
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.warm_floor
      temperature: '{{ states.input_number.day_temp.state }}'

- alias: "Night mode on"
  trigger:
  - platform: time
    at: "23:00:30"
  condition:
  - condition: state
    entity_id: climate.warm_floor
    state: heat
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.warm_floor
      temperature: '{{ states.input_number.night_temp.state }}'

- alias: 'Change Day Temp'
  trigger:
    - platform: state
      entity_id: input_number.day_temp
  condition:
  - condition: time
    after: '7:00:00'
    before: '23:00:00'
  - condition: and
    conditions:
    - condition: state
      entity_id: climate.warm_floor
      state: heat
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.warm_floor
        temperature: '{{ states.input_number.day_temp.state }}'

- alias: 'Change Night Temp'
  trigger:
    - platform: state
      entity_id: input_number.night_temp
  condition:
  - condition: time
    after: '23:00:00'
    before: '7:00:00'
  - condition: and
    conditions:
    - condition: state
      entity_id: climate.warm_floor
      state: heat
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.warm_floor
        temperature: '{{ states.input_number.night_temp.state }}'

# - alias: "Sensors update p14"
#   trigger:
#   - platform: time_pattern
#     seconds: "10"
#   condition: []
#   action:
#   - service: mqtt.publish
#     data: 
#       payload: "get:14"
#       topic: megad/14/cmd

# - alias: "Sensors update p30"
#   trigger:
#   - platform: time_pattern
#     seconds: "20"
#   condition: []
#   action:
#   - service: mqtt.publish
#     data: 
#       payload: "get:30"
#       topic: megad/14/cmd

# - alias: "Sensors update p31"
#   trigger:
#   - platform: time_pattern
#     seconds: "30"
#   condition: []
#   action:
#   - service: mqtt.publish
#     data: 
#       payload: "get:31"
#       topic: megad/14/cmd

# - alias: 'p3_bmx280_temp_update'
#     trigger:
#       - platform: time_pattern
#         minutes: '/1'
#     action:
#       - service: homeassistant.update_entity
#         entity_id: sensor.p3_bmx280_temp

# - alias: "Update all ports"
#     trigger:
#       - platform: time_pattern
#         seconds: "10"
#     action:
#       # - service: downloader.download_file
#       #   data_template:
#       #     url: "http://10.8.0.5:304/sec/?cmd=all"
#       #     filename: "megad.state"
#       #     overwrite: "true"
#       - service: homeassistant.update_entity
#         entity_id: 
#           - sensor.megad_state

# - initial_state: 'on'
#   alias: 'Megad hook'
#   trigger:
#     - platform: webhook
#       webhook_id: md
#   action:
#     - event: tasker_webhook
#       event_data_template:
#         who: "{{ trigger.json.who }}"
#         what: "{{ trigger.json.what }}"