
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  whitelist_external_dirs:
    - /home/fazenda/.homeassistant

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 365

# downloader:
#   download_dir: downloads
####################################################
#                                                  #
#           MegaD MQTT response exapmples          #
#                                                  #
####################################################
#OUT port
#{"port":7,"value":"OFF"}
#{"port":7,"value":"ON"}

#I2C port
#bmx280 sensor
#{"port":30,"value":{"temp":23.64,"press":729.86,"hum":38.556}}
#htu21d sensor
#{"port":31,"value":{"temp":23.96, "hum":43.71}}

#DSen port
#{"port":14,"value":"temp:23.62"}

####################################################
#                                                  #
#           MegaD MQTT command exapmples           #
#                                                  #
####################################################
#topic megad/14/cmd
#{"port":8,"value":"OFF"}
#{"port":8,"value":"ON"}
#{"port":14}

####################################################
#                                                  #
#           MegaD HTTP command & responses exapmples           #
#                                                  #
####################################################
#GET http://10.8.0.5:304/sec/?cmd=all // get current value for all ports
#OFF/0;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;temp:10.06;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;OFF;temp:10.24/press:728.92/hum:61.235;temp:10.66/hum:68.10;OFF;OFF;OFF;OFF;OFF;OFF
#GET http://10.8.0.5:304/sec/?pt=30&cmd=get // get value for any port
#temp:10.24/press:728.92/hum:61.247
#GET http://10.8.0.5:304/sec/?pt=30&scl=32&i2c_dev=bmx280&i2c_par=3
#temp:10.23/press:728.90/hum:61.245
#GET http://10.8.0.5:304/sec/?pt=30&scl=32&i2c_dev=bmx280&i2c_par=1
#10.24
#http://10.8.0.5:304/sec/?pt=7&cmd=get
#OFF
#http://10.8.0.5:304/sec/?pt=1&cmd=d // run default action for port 1

####################################################
#                                                  #
#                    sensor                        #
#                                                  #
####################################################
sensor:
  - platform: uptime
    name: HA Uptime
  - platform: filesize
    file_paths:
      - /home/fazenda/.homeassistant/home-assistant_v2.db
#   - platform: mqtt
#     name: "MQTT Температура p30 bmx280"
#     device_class: temperature
#     state_topic: "megad/14/30"
#     value_template: "{{ value_json.value.temp }}"
#     unit_of_measurement: "°C"
#     force_update: on
#   - platform: mqtt
#     name: "MQTT Давление p30 bmx280"
#     device_class: pressure
#     state_topic: "megad/14/30"
#     value_template: "{{ value_json.value.press }}"
#     unit_of_measurement: "hPa"
#     force_update: on
#   - platform: mqtt
#     name: "MQTT Влажность p30 bmx280"
#     device_class: humidity
#     state_topic: "megad/14/30"
#     value_template: "{{ value_json.value.hum }}"
#     unit_of_measurement: "%"
#     force_update: on      

  # - platform: rest
  #   name: p30_bmx280_temp
  #   friendly_name: "Температура p30 bmx280"
  #   device_class: temperature
  #   resource: http://10.8.0.5:304/sec/?pt=30&scl=32&i2c_dev=bmx280&i2c_par=1
  #   value_template: "{{value|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on
  # - platform: rest
  #   name: p30_bmx280_press
  #   friendly_name: "Давление p30 bmx280"
  #   device_class: pressure
  #   resource: http://10.8.0.5:304/sec/?pt=30&scl=32&i2c_dev=bmx280&i2c_par=0
  #   value_template: "{{value|float}}"
  #   unit_of_measurement: 'hPa'
  #   force_update: on
  # - platform: rest
  #   name: p30_bmx280_hum
  #   friendly_name: "Влажность p30 bmx280"
  #   device_class: humidity
  #   resource: http://10.8.0.5:304/sec/?pt=30&scl=32&i2c_dev=bmx280&i2c_par=2
  #   value_template: "{{value|float}}"
  #   unit_of_measurement: '%'
  #   force_update: on
  
  # - platform: command_line
  #   name: p30_bmx280_temp
  #   friendly_name: "Температура p30 bmx280"
  #   device_class: temperature
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[30].split('/')[0].split(':')[1]|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on 
  # - platform: command_line
  #   name: p30_bmx280_press
  #   friendly_name: "Давление p30 bmx280"
  #   device_class: pressure
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[30].split('/')[1].split(':')[1]|float}}"
  #   unit_of_measurement: 'hPa'
  #   force_update: on
  # - platform: command_line
  #   name: p30_bmx280_hum
  #   friendly_name: "Влажность p30 bmx280"
  #   device_class: humidity
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[30].split('/')[2].split(':')[1]|float}}"
  #   unit_of_measurement: '%'
  #   force_update: on

  # - platform: template
  #   sensors:
  #     p3_bmx280_press:
  #       friendly_name: "Давление p30 bmx280"
  #       #entity_id
  #       value_template: "{{ states.sensor.room_sensors.attributes["bedroom1"]["temperature"] }}"
  #       device_class: pressure
  #       unit_of_measurement: 'hPa'
  #     p3_bmx280_hum:
  #       friendly_name: "Влажность p30 bmx280"
  #       value_template: "{{ states.sensor.room_sensors.attributes["bedroom1"]["humidity"] }}"
  #       device_class: humidity
  #       unit_of_measurement: '%'

  # - platform: mqtt
  #   name: "MQTT Температура p31 htu21d"
  #   device_class: temperature
  #   state_topic: "megad/14/31"
  #   value_template: "{{ value_json.value.temp }}"
  #   unit_of_measurement: "°C"
  #   force_update: on
  # - platform: mqtt
  #   name: "MQTT Влажность p31 htu21d"
  #   device_class: humidity
  #   state_topic: "megad/14/31"
  #   value_template: "{{ value_json.value.hum }}"
  #   unit_of_measurement: "%"
  #   force_update: on    
  
  # - platform: rest
  #   name: p31_htu21d_temp
  #   friendly_name: "Температура p31 htu21d"
  #   device_class: temperature
  #   resource: http://10.8.0.5:304/sec/?pt=31&scl=32&i2c_dev=htu21d&i2c_par=1
  #   value_template: "{{value|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on
  # - platform: rest
  #   name: p31_htu21d_hum
  #   friendly_name: "Влажность p31 htu21d"
  #   device_class: humidity
  #   resource: http://10.8.0.5:304/sec/?pt=31&scl=32&i2c_dev=htu21d&i2c_par=0
  #   value_template: "{{value|float}}"
  #   unit_of_measurement: '%'
  #   force_update: on  

  # - platform: command_line
  #   name: p31_htu21d_temp
  #   friendly_name: "Температура p31 htu21d"
  #   device_class: temperature
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[31].split('/')[0].split(':')[1]|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on
  # - platform: command_line
  #   name: p31_htu21d_hum
  #   friendly_name: "Влажность p31 htu21d"
  #   device_class: humidity
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[31].split('/')[1].split(':')[1]|float}}"
  #   unit_of_measurement: '%'
  #   force_update: on  

  # - platform: mqtt
  #   name: MQTT ds18b20wp
  #   device_class: temperature
  #   state_topic: "megad/14/14"
  #   value_template: "{{ value_json.value[5:] }}"
  #   unit_of_measurement: "°C"
  #   force_update: on

  # - platform: rest
  #   name: p14_ds18b20wp_temp
  #   friendly_name: "Температура p14 ds18b20wp"
  #   device_class: temperature
  #   resource: http://10.8.0.5:304/sec/?pt=14&cmd=get
  #   value_template: "{{value[5:]|float}}"
  #   #value_template: "{{value|replace('temp:','')|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on
  
  # - platform: command_line
  #   name: p14_ds18b20wp_temp
  #   friendly_name: "Температура p14 ds18b20wp"
  #   device_class: temperature
  #   comand: "/bin/cat './downloads/megad.state'"
  #   value_template: "{{value.split(';')[14].split(':')[1]|float}}"
  #   unit_of_measurement: '°C'
  #   force_update: on

  - platform: rest
    name: megad_state
    resource: http://10.8.0.5:304/sec/?cmd=all
    value_template: "{{value}}"
    force_update: on
  - platform: template
    sensors:
      p30_bmx280_temp:
          friendly_name: "Температура p30 bmx280"
          device_class: temperature
          value_template: "{{states('sensor.megad_state').split(';')[30].split('/')[0].split(':')[1]|float|round(1)}}"
          unit_of_measurement: '°C'
      p30_bmx280_press:
          friendly_name: "Давление p30 bmx280"
          device_class: pressure
          value_template: "{{states('sensor.megad_state').split(';')[30].split('/')[1].split(':')[1]|float|round(1)}}"
          unit_of_measurement: 'hPa'
      p30_bmx280_hum:
          friendly_name: "Влажность p30 bmx280"
          device_class: humidity
          value_template: "{{states('sensor.megad_state').split(';')[30].split('/')[2].split(':')[1]|float|round(1)}}"
          unit_of_measurement: '%'
      p31_htu21d_temp:
          friendly_name: "Температура p31 htu21d"
          device_class: temperature
          value_template: "{{states('sensor.megad_state').split(';')[31].split('/')[0].split(':')[1]|float|round(1)}}"
          unit_of_measurement: '°C'
      p31_htu21d_hum:
          friendly_name: "Влажность p31 htu21d"
          device_class: humidity
          value_template: "{{states('sensor.megad_state').split(';')[31].split('/')[1].split(':')[1]|float|round(1)}}"
          unit_of_measurement: '%'
      p14_ds18b20wp_temp:
          friendly_name: "Температура p14 ds18b20wp"
          device_class: temperature
          value_template: "{{states('sensor.megad_state').split(';')[14].split(':')[1]|float|round(1)}}"
          unit_of_measurement: '°C'
  
  - platform: filter
    name: "filtered_p30_bmx280_hum"
    entity_id: sensor.p30_bmx280_hum
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 2

  - platform: filter
    name: "filtered_p31_htu21d_hum"
    entity_id: sensor.p31_htu21d_hum
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 2

#  - platform: mqtt
#    name: "Темп. кухня"
#    device_class: temperature
#    state_topic: "megad/14/7"
#    value_template: >- #еще вариант: https://community.home-assistant.io/t/trigger-numeric-state-below-value-not-firing/28911
#      {%- if value_json.value.ff4902731604|float >= 0 and value_json.value.ff4902731604|float <= 70 -%}
#      {{ value_json.value.ff4902731604 | round(1) }}
#      {%- else -%}
#      nan
#      {%- endif -%}
#    unit_of_measurement: "°C"
#  - platform: mqtt
#    name: "Датчик шума"
#    device_class: signal_strength
#    state_topic: "megad/14/36"
#    value_template: "{{ (value_json.value|float/1023*3.3*50) | round(1) }}"    
#    unit_of_measurement: "dBA"

####################################################
#                                                  #
#                    binary_sensor                 #
#                                                  #
####################################################
  
#binary_sensor:
#  - platform: mqtt
#    name: "Входная дверь"
#    device_class: door
#    state_topic: "megad/14/5"
#    value_template: "{{ value_json.value }}"
#    qos: 1
#    payload_on: "OFF"
#    payload_off: "ON"

####################################################
#                                                  #
#                    light                        #
#                                                  #
####################################################

#light:
#  - platform: mqtt
#    name: "Туалет"
#    state_topic: "stat/ElectroDragon1/RESULT"
#    value_template: "{{ value_json.POWER1 }}"
#    command_topic: "cmnd/ElectroDragon1/POWER1"
#    availability_topic: "tele/ElectroDragon1/LWT"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    payload_available: "Online"
#    payload_not_available: "Offline"

####################################################
#                                                  #
#                    switch                        #
#                                                  #
####################################################

switch:
  # - platform: mqtt
  #   name: MQTT heater
  #   icon: "mdi:radiator"
  #   state_topic: "megad/14/8"
  #   value_template: "{{ value_json.value }}"
  #   command_topic: "megad/14/cmd"
  #   payload_on: "8:1"
  #   payload_off: "8:0"
  #   state_on: "ON"
  #   state_off: "OFF"

  - platform: command_line
    switches:
      p7_heater:
        friendly_name: "Конвектор в бойлерной"
        command_on: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=7&cmd=7:1'"
        command_off: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=7&cmd=7:0'"
        command_state: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=7&cmd=get'"
        value_template: "{{ value == 'ON' }}"
        #command_state: "/bin/cat './downloads/megad.state'"
        #value_template: "{{ value.split(";")[7] == "ON" }}"
      p8_boiler:
        friendly_name: "Бойлер 150л"
        command_on: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=8&cmd=8:1'"
        command_off: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=8&cmd=8:0'"
        command_state: "/usr/bin/curl -X GET 'http://10.8.0.5:304/sec/?pt=8&cmd=get'"
        value_template: "{{ value == 'ON' }}"


climate:
  - platform: generic_thermostat
    name: termostat1
    heater: switch.p7_heater
    target_sensor: sensor.p14_ds18b20wp_temp
    min_temp: 7
    max_temp: 30
    min_cycle_duration:
      minutes: 5
    cold_tolerance: 1
    hot_tolerance: 1
    precision: 0.5
    initial_hvac_mode: "heat"
